### ISSUE TITLE
Minor edits needed for 7.10

### ISSUE THREAD

**Issue by athanclark** [tmcdonell/cuda#41]
Hey, I just ran into a couple of errors while building the code with `stack-7.10.yaml` - here's a commit that works for me, with this stack.yaml version: https://github.com/athanclark/cuda/commit/8b33fe4e5a3d28652f7bd01246e2fb0e6902a786

I'm not sure how it could be made backwards compatible though, especially with `findProgramOnSearchPath` returning a different type with Cabal 1.22 :\

**Comment by tmcdonell** [comment]
Thanks!

Yeah, it is a bit of a mess unfortunately. The `Setup.hs` has to work with cabal-1.24 because that is what ships with ghc-8, but there are no CPP macros or anything to try and determine what version you are on ): I'll have to try again and see if I can make it work though.

You can use `stack setup --upgrade-cabal` to upgrade your stack-installed ghc-7.10 to cabal-1.24, but that is a global operation so I dunno if it'll bite you for other packages...
